version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      MYSQL_HOST: db
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: myapp
    networks:
      - myapp-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    networks:
      - myapp-network

volumes:
  mysql-data:

networks:
  myapp-network:
